spring:
  datasource:
    url: jdbc:h2:mem:award;NON_KEYWORDS=YEAR
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

movelist-csv: movielist.csv